### ISSUE TITLE
Error on image rendering.

### ISSUE THREAD

**Issue by djnatedagreat** [matfish2/craft-blogify#3]
I've installed the trial version of Blogify v 2.0.3. I installed test data. When I try to visit `/blog/index` or one of the test posts with an image, I get the error: `Call to a member function setTransform() on null ... in /var/www/html/vendor/matfish/craft-blogify/src/behaviors/PostFieldsBehavior.php at line 23`. It shows the error to occur in the `thumbnail()` function.

**Comment by matfish2** [comment]
Hi @djnatedagreat 

The error you are reporting indicates that there is probably no image associated with at least one of the posts:
a. `listing._entry.twig:22` calls the `thumbnail` method:
`<img src="{{ post.thumbnail.url }}" alt="{{ post.thumbnail.title }}"`
b. `getImage` on `PostFieldsBehavior:17` returns `NULL` 
c. Consequently `setTransform` is called on `NULL`.

Can you please verify that all posts have an image associated with them? 

Couple more questions:
1. Did you generate the posts using the command : `php craft blogify/seed`? If so, did you receive any errors while running it? You can check the log file: `blogify-2023-08-{day}.log` 
3. Did you change any of the handles? The handle should be `blogifyPostImage`.

**Comment by djnatedagreat** [comment]
Hi and Many thanks for your help.
I was able to resolve the problem with your suggestions. I had created my own Blog entry, "Hello Worlud, which was missing an image and also missing a category. The omission of both of those things caused errors.
